#         _
# _______| |__  _ __ ___
#|_  / __| '_ \| '__/ __|
# / /\__ \ | | | | | (__
#/___|___/_| |_|_|  \___|

#########################
# Rafael Goncalves 2017 #
#########################

## Variables ##
###############
export INBOX=$HOME/inbox
export ARCHIVE=$HOME/archive
export MEDIA=$HOME/media
export IMAGES=$HOME/media/img
export MUSIC=$HOME/media/mus
export BUILDS=$HOME/builds
export SCRIPTS=$HOME/scripts
export BIN=$HOME/bin
export TMP=$HOME/tmp
export DOTFILES=$HOME/dotfiles

export PATH=$PATH:$SCRIPTS:$BIN:$BUILDS

export EDITOR="vim"
export USE_EDITOR=$EDITOR
export VISUAL=$EDITOR

export TERM=xterm-256color

source $DOTFILES/zsh/gitstatus.sh
source $HOME/.greengrocer.sh


## Configuration ##
###################

bindkey -v                  # Vim like bindings

setopt RM_STAR_WAIT         # Wait if rm something
setopt interactivecomments  # Allow comments in shell with '#'

#History
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt append_history       # integrated history between shell sessions
setopt extended_history     # save timestamp of command and duration
setopt inc_append_history   # Add comamnds as they are typed
setopt share_history        # appends typed commands to history
setopt HIST_IGNORE_DUPS     # Ignore duplicates

#Auto-completion
zstyle :compinstall filename 'home/rafael/.zshrc'
autoload -Uz    compinit
compinit
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}' #case insensitive

#Globbing
setopt NO_CASE_GLOB
setopt EXTENDED_GLOB
setopt NUMERIC_GLOB_SORT

#Unicode
source $DOTFILES/zsh/unicode.zsh

## Aliases ##
#############

#sudo
insert_sudo () { zle beginning-of-line; zle -U "sudo " }
zle -N insert-sudo insert_sudo
bindkey "^[s" insert-sudo

#history search
bindkey "^R" history-incremental-search-backward
bindkey "^P" history-search-backward
bindkey "^N" history-search-forward

#common comands
alias -g ls="ls --color"
alias -g la="ls -lah --color"
alias -g grep="grep --color"
alias -g ns="sudo netctl stop-all && sudo netctl start"

#cd
# If you type foo, and it isn't a command, and it is a directory in your cdpath, go there
setopt auto_cd

alias -g ...="../.."
alias -g ....="../../.."
alias -g .....="../../../.."

#common places
alias inbox="cd $INBOX"
alias archive="cd $ARCHIVE"
alias media="cd $MEDIA"
alias dotfiles="cd $DOTFILES"
alias img="cd $IMAGES"
alias mus="cd $MUSIC"
alias builds="cd $BUILDS"
alias scripts="cd $SCRIPTS"
alias bin="cd $BIN"
alias tmp="cd $TMP"

#editing conf files
alias zshrc="$EDITOR $DOTFILES/zsh/zshrc"
alias vimrc="$EDITOR $DOTFILES/vim/vimrc"
alias tmuxconf="$EDITOR $DOTFILES/tmux/conf"
alias termiteconf="$EDITOR $HOME/.config/termite/config"
alias i3conf="$EDITOR $HOME/.config/i3/config"
alias rangerc="$EDITOR $HOME/.config/ranger/rc.conf"

## Prompt ##
############
set PROMPT_SUBST
set PROMPT_BANG
set PROMPT_PERCENT

autoload -U colors && colors
autoload -Uz promptinit
promptinit

autoload -Uz chpwd_recent_dirs cdr add-zsh-hook
add-zsh-hook chpwd chpwd_recent_dirs

#LPrompt
##White Prompt
#PROMPT='[%n@%m %{$fg_bold[white]%}%1~%{$reset_color%}]%(!.#.$) '
##Cyan Prompt
#PROMPT='%{$fg[cyan]%}[%n@%m %{$fg_bold[cyan]%}%1~%{$reset_color%}%{$fg[cyan]%}]%(!.#.$) %{$reset_color%}'
##Pink Prompt
PROMPT='%{$fg[red]%}[%n@%m %{$fg_bold[red]%}%1~%{$reset_color%}%{$fg[red]%}]%(!.#.$) %{$reset_color%}'

#RPrompt
RPROMPT='$(git_super_status) %(1j.[%j].)'

